import type { Metadata } from "next";
import Navbar from "@/components/nav";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-secondary-300 to-primary-300 text-neutral-900">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
